Upgrade GitHub actions and Hugo
The upload-pages-artifact@v2 seems to depend on deprecated upload-artifact action:
Error: Missing download info for actions/upload-artifact@v3